Westminster Pride Store/PythonProjects/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from testStore import views
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.shortcuts import render, get_object_or_404, redirect, reverse

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('testStore/', include('django.contrib.auth.urls')),  # new
    path('testStore/product<slug>/', views.ProductView.as_view(), name='product'),
    path('testStore/add_to_cart<slug>/', views.add_to_cart, name='add_to_cart'),
    path('testStore/remove_from_cart<id>/', views.remove_from_cart, name='remove_from_cart'),
    path('testStore/cart/', views.CartView.as_view(), name='cart'),
    path('testStore/checkout/', views.OrderForm.as_view(), name='checkout'),
    path('add_form/', views.AddForm.as_view(), name='add_prod'),
    path('size_form/', views.AddSize.as_view(), name='add_size'),
    path('admin/', admin.site.urls),
    path('owner/', views.OwnerPage.as_view(), name='owner'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Westminster Pride Store/testStore/models.py
from djmoney.models.fields import MoneyField
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from importlib import import_module
from django.contrib.sessions.backends.db import SessionStore


# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)
    price = MoneyField(max_digits=14, decimal_places=2, default_currency='USD')
    photo1 = models.ImageField(upload_to='media/', blank=True, null=True)
    photo2 = models.ImageField(upload_to='media/', blank=True, null=True)
    slug = models.SlugField(null=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("add_to_cart", kwargs={
            'slug': self.slug
        })


class Size(models.Model):
    Size_Choice = [
        ('XS', 'XS'),
        ('SM', 'SM'),
        ('MD', 'MD'),
        ('LG', 'LG'),
        ('XL', 'XL'),
        ('2XL', '2XL'),
        ('3XL', '3XL'),
        ('4XL', '4XL')
    ]
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    size = models.CharField(max_length=4, null=True, choices=Size_Choice)
    price = MoneyField(max_digits=14, decimal_places=2, default_currency='USD')
    qty = models.IntegerField(default=0)
    in_stock = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.size}"

    def get_absolute_url(self):
        return reverse("product", kwargs={
            'slug': self.product.slug
        })


class CartItem(models.Model):
    session = models.CharField(max_length=200, null=True, default='noSessionID')
    item = models.ForeignKey(Product, on_delete=models.CASCADE, null=False)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, null=True)
    qty = models.IntegerField(default=1, null=False)

    def total_price(self):
        return self.qty * self.size.price

    def __str__(self):
        return f"{self.qty} of {self.item} size {self.size} "


class Cart(models.Model):
    session = models.CharField(max_length=200, null=True, default='noSessionID')
    item = models.ManyToManyField(CartItem)
    slug = models.SlugField(null=False)

    def order_total(self):
        total = 0
        for item in self.item.all():
            total += item.total_price()
        return total

    def __str__(self):
        return f"{self.id} "

Westminster Pride Store/testStore/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from .models import Product
from .models import Size
from .models import CartItem
from .models import Cart
from django.template import loader
from django.views.generic import ListView, DetailView, View, CreateView, FormView, TemplateView
import sys
import logging
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login


class OwnerPage(TemplateView):
    template_name = 'owner.html'
    # def get(self, request, *args, **kwargs):
    #     return HttpResponse('owner.html')


class AddForm(LoginRequiredMixin, CreateView):
    login_url = '/testStore/login/'
    model = Product
    fields = [
        'name',
        'price',
        'photo1',
        'photo2',
        'slug'
    ]


class AddSize(LoginRequiredMixin, CreateView):
    login_url = '/testStore/login/'
    model = Size
    fields = [
        'product',
        'size',
        'price',
        'qty',
        'in_stock'
    ]


class ProductView(DetailView):
    model = Product
    template_name = "productPage.html"


class HomeView(ListView):
    model = Product
    template_name = "storeFront.html"


class CartView(View):
    def get(self, *args, **kwargs):
        try:
            cart = Cart.objects.get(session=self.request.session.session_key)
            context = {
                'object': cart
            }
            return render(self.request, 'cart.html', context)
        except ObjectDoesNotExist:
            return render(self.request, "cart.html")


class OrderForm(View):
    def get(self, *args, **kwargs):
        try:
            cart = Cart.objects.get(session=self.request.session.session_key)
            context = {
                'object': cart
            }
            return render(self.request, 'orderForm.html', context)
        except ObjectDoesNotExist:
            return render(self.request, "orderForm.html")


def add_to_cart(request, slug):
    if not request.session.exists(request.session.session_key):
        request.session.create()

    request.session.save()
    session_id = request.session.session_key
    new_item = get_object_or_404(Product, slug=slug)
    size = ''
    qty = int
    if request.method == "POST":
        for item in request.POST:
            if item == 'qty':
                key = item
                qty = int(request.POST[key])
                print(qty, type(qty), flush=True)
            elif item == 'size':
                key = item
                print(key, flush=True)
                item_size = request.POST[key]
                print(item_size, flush=True)
                if Size.objects.filter(size=item_size, product=new_item).exists():
                    size_object = Size.objects.filter(size=item_size, product=new_item)
                    size = size_object[0]

    cart_item, created = CartItem.objects.get_or_create(item=new_item, size=size, session=session_id)
    cart_qs = Cart.objects.filter(session=session_id)
    print(request.session.session_key, flush=True)

    if cart_qs.exists():
        cart = cart_qs[0]
        item_qs = cart.item.filter(item=cart_item.item)
        if item_qs.exists():
            for item in item_qs:
                if item.size == size:
                    cart_item.qty += qty
                    cart.item.add(cart_item)
                    cart_item.save()
                else:
                    cart_item.qty = qty
                    cart.item.add(cart_item)
                    cart_item.save()
        else:
            cart_item.qty = qty
            cart_item.save()
            cart.item.add(cart_item)
    else:
        cart = Cart.objects.create(session=request.session.session_key)
        cart_item.qty = qty
        cart_item.save()
        cart.item.add(cart_item)
        cart.save()
    messages.success(request, 'Item Added to Cart!')
    return redirect("product", slug=slug)


def remove_from_cart(request, id):
    request.session.save()
    item = CartItem.objects.get(id=id)

    item.delete()
    return redirect("cart")

Westminster Pride Store/templates/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shopping Cart</title>
        <link href="https://fonts.googleapis.com/css?family=Merriweather&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ MEDIA_URL }}/media/media/pridestyle.css">

{#<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>#}
</head>
<body>
<div class = "header" style="text-align: center">
    <a href= {% url 'home' %}> <img src="{{ MEDIA_URL }}/media/media/banner.png" style= "max-width:60vw; text-align: center"></a>
  </div>
<h2 style="text-align: center"> Shopping Cart</h2>


<table id="cart" style="width: 50vw; margin: 0px auto">
<thead>
    <tr align="left">
        <th>Product</th>
        <th>Size</th>
        <th>Quantity</th>
    </tr>
</thead>
<tbody>
{% for CartItem in object.item.all %}
    <tr align="left">
        <td>{{ CartItem.item }}</td>
        <td>{{ CartItem.size }}</td>
        <td>{{ CartItem.qty }}<td>
        <td>{{ CartItem.total_price }}</td>
        <td> <a href="{% url 'remove_from_cart' CartItem.id %}"> Remove </a></td>
    </tr>
    {% empty %}
    <h2 style="text-align: center">Your Cart is empty!</h2>
        <script>
            function hide() {
            let f = document.getElementById("cart");
            if (f.style.display === "none") {
            f.style.display = "block";
            }
                else {
                f.style.display = "none";
            }
        }
        hide()
        </script>
{% endfor %}
<tr>
<td>   </td>
</tr>
<tr>
<td>   </td>
</tr>
<tr style="padding: 50px">
    <td colspan="4"><b> Total: </b></td>
    <td colspan="1" align="left"><b>{{ object.order_total }}</b></td></tr>

</tbody>
</table>
<br>
<br>
<br>
<div style="text-align: center">
    <a style="text-align: center" class="buttoncart" href= {% url 'home' %}> Continue Shopping </a>
    </div>
<br>
<div style="text-align: center">
<a class="buttoncart" href= {% url 'checkout' %}> Checkout </a>
</div>

</div>

</body>
</html>

Westminster Pride Store/templates/orderForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Place Order</title>
</head>
<body>
<div class = "header" style="text-align: center">
    <a href= {% url 'home' %}> <img src="{{ MEDIA_URL }}/media/media/banner.png" style= "max-width:60vw; text-align: center"></a>
  </div>



</body>
</html>

Westminster Pride Store/templates/owner.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Owner</title>
</head>
<body>

<h2>What would you like to do? </h2>

<a href= "{% url 'add_prod' %}"> Add a New Product</a>
<br>
<a href="{% url 'add_size' %}"> Add Sizes to Product</a>


</body>
</html>

Westminster Pride Store/templates/productPage.html
<!DOCTYPE html>
<html lang="en">

    <link rel="stylesheet" href="{{ MEDIA_URL }}/media/media/pridestyle.css">
 <head>
    {% load static %}
    <meta charset="UTF-8">
    <style>
        body {
  		font-family: "Lato";
            color: #8252c7;
			}
    </style>

<link href="https://fonts.googleapis.com/css?family=Merriweather&display=swap" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <title> Product Page </title>

</head>
<body>
<div class = "header" style="text-align: center">
    <a href= {% url 'home' %}> <img src="{{ MEDIA_URL }}/media/media/banner.png" style= "max-width:60vw; text-align: center"></a>
  </div>

{% if messages %}
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
{% endif %}

<!-- attempt 2 -->
<div style="width:55vw; margin: auto">
<div class= "p" style="width: 60%; margin: auto; text-align: center; float: left">

    <img class="slide" src="{{MEDIA_URL}}{{ product.photo2.url }}" style="width: 30vw">
</div>

<div style="float: right; width: 40%;">
<div style="font-size: 24px; font-weight: bold; color: #211551"> {{ product.name }}</div>
    <div style="font-size: 20px" id="product">{{ product.price }}</div>

    <form id='add_to_cart' method="POST" action="{% url 'add_to_cart' product.slug %}"> {% csrf_token %}
        <div style="color: #211551; font-size: 20px">Size:

    <select id = 'select_size' name="size"  style="color: #211551; font-size: 16px; border-color: #211551; border-width: 1px">
        {% for item in product.size_set.all %}
        <option value="{{ item.size }}"} > {{ item.size }} {{ item.price }} </option>
        {% endfor %}
    </select>
    <br>

    <div style="font-size: 20px; padding-top: 10px; color: #211551;"> Quantity:
            <input style="font-size: 16px; border-color: #211551; border-width: 1px" type="number" name="qty"  min="1"  max="10" value="1" required/>
    </div>
        <br>
    <input class ="buttoncart" type="submit" value="Add To Cart"/>
<br>
</form>
<div>
    <div style="padding-top: 14px"><a class="buttoncart" href= {% url 'home' %}> Continue Shopping </a></div>
	<div style="padding-top: 20px"><a class="buttoncart" href = "{% url 'cart' %}"> Checkout </a></div>
    </div>
</div>

<h2 id="gone" style="display: none; text-align: center"> Out of Stock</h2>

<script>
{% if product.size_set.count == 0 %}
    hide()
        {% endif %}
</script>
<br>
</div>

</body>

<script>
    function hide() {
        let f = document.getElementById("add_to_cart");
        let g = document.getElementById("gone");
        if (f.style.display === "none") {
        f.style.display = "block";
        {#g.style.display = "block";#}
        } else {
            f.style.display = "none";
            g.style.display = "block";
        }
    }
</script>
</html>

Westminster Pride Store/templates/storeFront.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Merriweather&display=swap" rel="stylesheet">
	
    <link rel="stylesheet" href="{{ MEDIA_URL }}/media/media/pridestyle.css">
   
         <title>Store Front </title>

    <style>
        body {
  		font-family: "Merriweather";
        color: #8252c7;
    </style>
</head>
<body>
<div style="padding-top: 5px; padding-bottom: 20px; float: right"><a class="buttoncart" href = "{% url 'cart' %}"> Cart </a></div>

<div class = "headerborder" style="text-align: center">
    <img class="photobanner" src="{{ MEDIA_URL }}/media/media/banner.png" style= "max-width:60vw; text-align: center">
  </div>

<h1 class="welcome" style="text-align: center;"> Welcome to the Westminster Pride Store</h1>

{#{% if object_list %}#}
{#     {% for product in object_list %}#}
{##}
{##}
{#         <table class ="productRow" style= "display: inline-block; width:auto">#}
{#             <tr><th> <a href = "{{ product.get_absolute_url }}">{{ product.name}}</a></th></tr>#}
{#            <tr>#}
{#                <td class="storeimg">  <a href = "{{ product.get_absolute_url }}">#}
{#                    <img src="{{MEDIA_URL}}{{ product.photo1.url }}"></a></td>#}
{#            </tr>#}
{#         </table>#}
{#         <br>#}
{#         <br>#}
{#    {% endfor %}#}
{##}
{#{% else %}#}
{#    <p>No products are available.</p>#}
{#{% endif %}#}



{% if object_list %}
     {% for product in object_list %}

         <div style="float:left; margin: auto; padding-left: 8vw; padding-top: 10px; padding-bottom: 20px">
             <div style="text-align: center; font-family: 'Merriweather'; font-size: 30px"> <a style="text-decoration: none" href = "{{ product.get_absolute_url }}">{{ product.name}}</a></div>
             <div style="text-align: center; font-family: 'Merriweather'; font-size: 20px"> {{ product.price}}</div>

            <div style="text-align: center; border: 4px #8252c7 solid"> <a href = "{{ product.get_absolute_url }}">
                <img style="height: 20vw" src="{{MEDIA_URL}}{{ product.photo1.url }}"></a>
            </div>
         </div>
{#         <table class ="productRow" style= "display: inline-block; width:auto">#}
{#             <tr><th> <a href = "{{ product.get_absolute_url }}">{{ product.name}}</a></th></tr>#}
{#            <tr>#}
{#                <td class="storeimg">  <a href = "{{ product.get_absolute_url }}">#}
{#                    <img src="{{MEDIA_URL}}{{ product.photo1.url }}"></a></td>#}
{#            </tr>#}
{#         </table>#}
{#         <br>#}
{#         <br>#}
    {% endfor %}

{% else %}
    <p>No products are available.</p>
{% endif %}

</body>
</html>

Westminster Pride Store/templates/testStore/product_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Form</title>
</head>
<body>
<h1> Add New Products</h1>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

</body>
</html>

Westminster Pride Store/templates/testStore/size_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Size Form</title>
</head>
<body>
<h2> Add a new size option: </h2>
<form method="post" enctype="multipart/form-data" action= {% url 'home' %}>{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>